### ISSUE TITLE
Grammar Check Incorrect

### ISSUE THREAD

**Issue by jmgrafixx** [markfullmer/grammark#17] opened 2020-06-17 11:47 UTC
I notice that, when submitting text to check with deliberate spelling mistakes and grammar errors, the script does not pick up any (or only a few) grammar mistakes. With the 'vintage' version of this script, the spelling errors are at least caught.

**Comment by markfullmer** [comment] 2020-08-28 18:26
Closing -- this is by design: general spelling & grammar mistakes are considered outside of the purview of this tool. There are many other spellcheckers available, so there is not much value in reproducing them within this tool. This tools is focused on grammatical elements that are not typically diagnosed by other checkers, namely, nominalizations, (over)use of passive voice, transitions, eggcorns.

**Closed by markfullmer** 2020-08-28 18:26 UTC
